# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"]\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\"7\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1c\n\x0eGetTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x10ListTodosRequest\x12\x16\n\tcompleted\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x0c\n\n_completed\".\n\x11ListTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"V\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9f\x02\n\x0bTodoService\x12\x31\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\n.todo.Todo\x12+\n\x07GetTodo\x12\x14.todo.GetTodoRequest\x1a\n.todo.Todo\x12<\n\tListTodos\x12\x16.todo.ListTodosRequest\x1a\x17.todo.ListTodosResponse\x12\x31\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\n.todo.Todo\x12?\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponseB(Z&github.com/saisai/grpc-todo/proto;todob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/saisai/grpc-todo/proto;todo'
  _globals['_TODO']._serialized_start=20
  _globals['_TODO']._serialized_end=113
  _globals['_CREATETODOREQUEST']._serialized_start=115
  _globals['_CREATETODOREQUEST']._serialized_end=170
  _globals['_GETTODOREQUEST']._serialized_start=172
  _globals['_GETTODOREQUEST']._serialized_end=200
  _globals['_LISTTODOSREQUEST']._serialized_start=202
  _globals['_LISTTODOSREQUEST']._serialized_end=258
  _globals['_LISTTODOSRESPONSE']._serialized_start=260
  _globals['_LISTTODOSRESPONSE']._serialized_end=306
  _globals['_UPDATETODOREQUEST']._serialized_start=308
  _globals['_UPDATETODOREQUEST']._serialized_end=394
  _globals['_DELETETODOREQUEST']._serialized_start=396
  _globals['_DELETETODOREQUEST']._serialized_end=427
  _globals['_DELETETODORESPONSE']._serialized_start=429
  _globals['_DELETETODORESPONSE']._serialized_end=466
  _globals['_TODOSERVICE']._serialized_start=469
  _globals['_TODOSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
